# Generated by Django 3.2.5 on 2021-08-09 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='posting_rights',
            field=models.ManyToManyField(blank=True, null=True, related_name='has_posting_rights_of', to='core.Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
