# Generated by Django 3.2.5 on 2021-08-05 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('privacy', models.CharField(choices=[('PBLC', 'Public'), ('EMAL', 'All Employees'), ('EMDP', 'All Employees of Selected Departments'), ('CMAL', 'All Chairmen'), ('CMDP', 'CHariman of Selected Departments')], max_length=5)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(related_name='posts', to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_original', models.ImageField(max_length=255, upload_to='images')),
                ('image_sm', models.ImageField(max_length=255, upload_to='images')),
                ('image_md', models.ImageField(max_length=255, upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.post')),
            ],
        ),
    ]
